// Expo config plugin: declare Google Wallet + Google Play Services in `<queries>`.
//
// On Android 11+ (package visibility) `PackageManager.queryIntentActivities(...)` / `resolveActivity`
// only see packages we've declared. The pass "Add to wallet" flow (`modules/pgfy-wallet`) sends the
// pass image to Wallet's photo importer, which lives in Google Play Services
// (`com.google.android.gms`, a `.../pay/...` activity), NOT the Wallet app package — so GMS must be
// visible for the direct-send to resolve. The Wallet app package is kept visible too (used for the
// "install Google Wallet" store fallback). `android/` is regenerated by `expo prebuild`, so this
// re-applies on every prebuild. Merged into the existing `<queries>` element.
const { withAndroidManifest } = require('@expo/config-plugins');

const PACKAGES = ['com.google.android.gms', 'com.google.android.apps.walletnfcrel'];

module.exports = function withWalletQueries(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.queries = manifest.queries || [];
    if (!manifest.queries.length) manifest.queries.push({});
    const target = manifest.queries[0];
    target.package = target.package || [];

    for (const name of PACKAGES) {
      const declared = manifest.queries.some((query) =>
        (query.package || []).some((pkg) => pkg?.$?.['android:name'] === name),
      );
      if (!declared) target.package.push({ $: { 'android:name': name } });
    }

    return cfg;
  });
};
