// Expo config plugin: wire a release signing config into the generated Android project.
//
// `android/` is regenerated by `expo prebuild` (and wiped by `prebuild --clean`), so the
// signing setup can't live only in `android/app/build.gradle`. This plugin re-applies it
// on every prebuild:
//   1. Copies the durable keystore + properties from `credentials/` into the android tree.
//   2. Adds a `release` signingConfig that reads `android/keystore.properties`.
//   3. Points the `release` build type at it — falling back to the debug key when the
//      keystore is absent, so plain dev prebuilds still build.
//
// Secrets live in `credentials/` (gitignored), never in the repo.
const { withAppBuildGradle, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Inserted into the `signingConfigs { ... }` block.
const RELEASE_SIGNING_CONFIG = `        release {
            def keystorePropertiesFile = rootProject.file("keystore.properties")
            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
`;

function applySigningConfig(contents) {
  // Idempotent: a second prebuild over an already-transformed file is a no-op.
  if (contents.includes('signingConfigs.release')) {
    return contents;
  }

  // 1) Add the `release` signing config after the generated `debug` one.
  const debugSigningBlock = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;
  const withReleaseSigning = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
${RELEASE_SIGNING_CONFIG}    }`;

  if (!contents.includes(debugSigningBlock)) {
    throw new Error(
      '[withAndroidSigning] Could not find the expected debug signingConfigs block in build.gradle. ' +
        'The Expo template may have changed; update plugins/withAndroidSigning.js.'
    );
  }
  contents = contents.replace(debugSigningBlock, withReleaseSigning);

  // 2) Point the release build type at the release signing config (debug fallback).
  const releaseDebugSigning = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;
  const releaseSigning = `            signingConfig rootProject.file("keystore.properties").exists() ? signingConfigs.release : signingConfigs.debug`;

  if (!contents.includes(releaseDebugSigning)) {
    throw new Error(
      '[withAndroidSigning] Could not find the expected release buildType signingConfig in build.gradle. ' +
        'The Expo template may have changed; update plugins/withAndroidSigning.js.'
    );
  }
  contents = contents.replace(releaseDebugSigning, releaseSigning);

  return contents;
}

function copyCredentials(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const { projectRoot, platformProjectRoot } = config.modRequest;
      const srcKeystore = path.join(projectRoot, 'credentials', 'release.keystore');
      const srcProps = path.join(projectRoot, 'credentials', 'keystore.properties');

      if (fs.existsSync(srcKeystore)) {
        fs.copyFileSync(srcKeystore, path.join(platformProjectRoot, 'app', 'release.keystore'));
      } else {
        console.warn(
          '[withAndroidSigning] credentials/release.keystore not found — release builds will fall back to the debug key.'
        );
      }
      if (fs.existsSync(srcProps)) {
        fs.copyFileSync(srcProps, path.join(platformProjectRoot, 'keystore.properties'));
      }
      return config;
    },
  ]);
}

module.exports = function withAndroidSigning(config) {
  config = copyCredentials(config);
  config = withAppBuildGradle(config, (config) => {
    config.modResults.contents = applySigningConfig(config.modResults.contents);
    return config;
  });
  return config;
};
