// Expo config plugin: declare the SnapKYC / UIDAI Aadhaar app in `<queries>`.
//
// On Android 11+ (package visibility), an app can't *see* another app's activities unless it
// declares them in `<queries>`. React Native's `Linking.sendIntent` guards with
// `intent.resolveActivity()`, which returns null for an invisible target — so launching the
// Aadhaar KYC intent fails with "could not open the Aadhaar app" even though `adb shell am
// start` (shell has full visibility) works. This makes the action visible so the launch
// succeeds. `android/` is regenerated by `expo prebuild`, so the query can't live only in the
// committed manifest — this re-applies it on every prebuild.
const { withAndroidManifest } = require('@expo/config-plugins');

const AADHAAR_ACTION = 'in.gov.uidai.pehchaan.WEB_INTENT_REQUEST';

module.exports = function withAadhaarQueries(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.queries = manifest.queries || [];

    const alreadyDeclared = manifest.queries.some((query) =>
      (query.intent || []).some((intent) =>
        (intent.action || []).some((action) => action?.$?.['android:name'] === AADHAAR_ACTION),
      ),
    );

    if (!alreadyDeclared) {
      manifest.queries.push({
        intent: [{ action: [{ $: { 'android:name': AADHAAR_ACTION } }] }],
      });
    }

    return cfg;
  });
};
